; Configuration file for Duet 3 Mini 5+ (firmware version 3.3)
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Tue Nov 28 2023 13:41:44 GMT+0000 (Greenwich Mean Time)

; General preferences
M575 P1 S1 B57600                                  ; enable support for PanelDue
G90                                                ; send absolute coordinates...
M83                                                ; ...but relative extruder moves
M550 P"LulzBot"                                    ; set printer name
M918 P1 E4 F2000000                                ; configure direct-connect display

; Network
M552 P192.168.2.6 S1                               ; enable network and set IP address
M553 P255.255.255.0                                ; set netmask
M554 P192.168.1.254                                ; set gateway
M586 P0 S1                                         ; enable HTTP
M586 P1 S0                                         ; disable FTP
M586 P2 S0                                         ; disable Telnet

; Drives
M569 P0 S0 D3 V10
M569 P1 S1 D3 V10                                        ; physical drive 0.1 goes backwards X
M569 P2 S1 D3 V100                                      ; physical drive 0.2 goes forwards	Z
M569 P3 S1 D3 V100									
M569 P4 S0 D3 V10                                      ; C
M569 P5 S0 D3 V0
M569 P6 S0 D3 V0
M584 X1 Y0 Z2:3 B4 E5:6                         ; set drive mapping
M350 X16 Y16 Z16 B16 E16:16 I1                            ; configure microstepping with interpolation

M92 X100.00 Y100.00 Z1600.00 B880 E833:860                ; set steps per mm
M566 X900.00 Y900.00 Z60.00 B500.00 E300:300                ; set maximum instantaneous speed changes (mm/min)
M203 X6000.00 Y6000.00 Z600.00 B10000.00 E7200:7200         ; set maximum speeds (mm/min)
M201 X500.00 Y500.00 Z200.00 B5000.00 E2000:E2000                ; set accelerations (mm/s^2)
M906 X800 Y800 Z800 B670 E700:700 I30                       ; set motor currents (mA) and motor idle factor in per cent
M84 S30                                            ; Set idle timeout

; Axis Limits
M208 X0 Y0 Z0 B-360 S1                                   ; set axis minima
M208 X300 Y300 Z300 B360 S0                             ; set axis maxima
M564 H0

; Endstops
M574 X1 S1 P"!io5.in"                               ; configure switch-type (e.g. microswitch) endstop for low end on X via pin io5.in
M574 Y1 S1 P"!io6.in"                               ; configure switch-type (e.g. microswitch) endstop for low end on Y via pin io6.in
M574 Z1 S1 P"!io3.in"                               ; configure switch-type (e.g. microswitch) endstop for low end on Z via pin io2.in

; Z-Probe
M558 P0 H5 F120 T6000                              ; disable Z probe but set dive height, probe speed and travel speed
M557 X5:190 Y5:195 S10                             ; define mesh grid

; Heaters
; Bed Heater
M308 S0 P"temp0" Y"thermistor" B4725 C7.060000e-8 	; configure sensor 0 as thermistor on pin temp1
M950 H0 C"out0" Q25 T0                              ; create bed heater output on out0 and map it to sensor 0, PWMfrequency: 25Hz
M307 H0 R0.262 C338.0 D10.52 S1.00 V11.8 B0			; Bed tuning values, enable PID
M140 H0                                                    	; Bed uses Heater 0
M143 H0 S120                                               ; Set temperature limit for heater 0 to 120C Bed

; Hotend heater 1 (E)
M308 S1 P"temp1" Y"thermistor" B4725 C7.060000e-8 			; configure sensor 1 as thermistor on pin temp0
M950 H1 C"out1" T1                           				; create nozzle heater output on out1 and map it to sensor 1
M307 H1 B0 S1.00                             				; disable bang-bang mode for heater  and set PWM limit
M143 H1 S230                                 				; set temperature limit for heater 1 to 295C
M302 S170 R50                                        			; allow extrusion starting from 170°C and retractions already from 170°C

; Hotend heater 2 (N)
M308 S2 P"temp2" Y"thermistor" B4725 C7.060000e-8
M950 H2 C"out2" T2
M307 H2 B0 S1.00
M143 H2 S230
M302 S170 R50


; Fans
; Hotend cooling fan (1) E
M950 F1 C"out5" Q5000							; NOCTUA fan an pin out6 with 5000Hz PWM frequency
M106 P1 T35 S255 H1  							; Temperature control: turn fan on at 55°C

; Tools
; Hotend cooling fan (2) N
M950 F2 C"out6" Q5000							; NOCTUA fan an pin out6 with 5000Hz PWM frequency
M106 P2 T35 S255 H2  							; Temperature control: turn fan on at 55°C

M563 P0 S"T0" D0 H1 F1   ; define tool 0 (Hotend heater 1)
G10 P0 X0 Y0 Z0 B0 ; set tool 0 axis offsets
G10 P0 R0 S0 

M563 P1 S"T1" D1 H2 F2   ; define tool 1 (Hotend heater 2)
G10 P1 X0 Y0 Z0 B0 ; set tool 1 axis offsets
G10 P1 R0 S0 

M572 D0 S0.06


; Custom settings are not defined

M18 X Y Z B E 

