; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Tue Nov 28 2023 13:41:44 GMT+0000 (Greenwich Mean Time)


G91
G1 H2 Z3 F6000
G1 H1 Y-250 F1800
G1 H2 Y5 F6000
G1 H1 Y-255 F1800
G1 H2 Y5 F4800
G1 H2 Z-3 F4800
G90

