; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Tue Nov 28 2023 13:41:45 GMT+0000 (Greenwich Mean Time)

