; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Fri Nov 17 2023 19:59:21 GMT+0000 (Greenwich Mean Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


