; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Fri Nov 17 2023 19:59:21 GMT+0000 (Greenwich Mean Time)

