; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Fri Nov 17 2023 19:59:21 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

